name: My first workflow

on: [push]

jobs:
  myfirstjob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: AWS key setup
        uses: aws-actions/configure-aws-credentials@v1  
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: AWS CLI check
        run: aws --version

      - name: List S3 buckets
        run: aws s3 ls
